version: 2.1

jobs:
  "openjdk-11":
    working_directory: ~/circleci-greenmail

    docker:
        - image: azul/zulu-openjdk:11.0.23
          auth:
            username: $DOCKERHUB_IDENTITY
            password: $DOCKERHUB_PASSWORD
          environment:
            TZ: UTC

    steps:
      - checkout

      - restore_cache:
          key: greenmail-{{ checksum "pom.xml" }}

      - run: ./mvnw --batch-mode -V package -DskipTests dependency:resolve-plugins dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: greenmail-{{ checksum "pom.xml" }}

      - run:
          command: ./mvnw --batch-mode -V --fail-at-end --errors install
          no_output_timeout: 15m

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
 
  "openjdk-17":
    working_directory: ~/circleci-greenmail

    docker:
        - image: azul/zulu-openjdk:17.0.11
          auth:
            username: $DOCKERHUB_IDENTITY
            password: $DOCKERHUB_PASSWORD
          environment:
            TZ: UTC

    environment:
      MAVEN_HOME: /usr/share/maven
    steps:
      - checkout

      - restore_cache:
          key: greenmail-{{ checksum "pom.xml" }}

      - run: ./mvnw --batch-mode -V package -DskipTests dependency:resolve-plugins dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: greenmail-{{ checksum "pom.xml" }}

      - run:
          command: ./mvnw --batch-mode -V --fail-at-end --errors install
          no_output_timeout: 15m

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

  "openjdk-21":
    working_directory: ~/circleci-greenmail

    docker:
        - image: azul/zulu-openjdk:21.0.3
          auth:
            username: $DOCKERHUB_IDENTITY
            password: $DOCKERHUB_PASSWORD
          environment:
            TZ: UTC

    environment:
      MAVEN_HOME: /usr/share/maven
    steps:
      - checkout

      - restore_cache:
          key: greenmail-{{ checksum "pom.xml" }}

      - run: ./mvnw --batch-mode -V package -DskipTests dependency:resolve-plugins dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: greenmail-{{ checksum "pom.xml" }}

      - run:
          command: ./mvnw --batch-mode -V --fail-at-end --errors install
          no_output_timeout: 15m

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
workflows:
  version: 2
  build:
    jobs:
      - openjdk-11:
          context:
            - docker
      - openjdk-17:
          context:
            - docker
      - openjdk-21:
          context:
            - docker
